import type {
  Assessment,
  AssessmentLineItem,
  AssessmentComparison,
  BenchmarkFile,
  BenchmarkProcedure,
  ManagedUser,
} from "./types"

export const mockManagedUsers: ManagedUser[] = [
  { id: "mu-1", email: "sarah.johnson@takeda.com", fullName: "Sarah Johnson", securityGroups: ["USBU", "GME"], role: "ADMIN" },
  { id: "mu-2", email: "mike.chen@takeda.com", fullName: "Mike Chen", securityGroups: ["OBU"], role: "ANALYST" },
  { id: "mu-3", email: "emily.martinez@takeda.com", fullName: "Emily Martinez", securityGroups: ["GME", "VBU"], role: "APPROVER" },
  { id: "mu-4", email: "david.kim@takeda.com", fullName: "David Kim", securityGroups: ["PDT"], role: "ANALYST" },
  { id: "mu-5", email: "lisa.wong@takeda.com", fullName: "Lisa Wong", securityGroups: ["VBU"], role: "VIEWER" },
  { id: "mu-6", email: "james.miller@takeda.com", fullName: "James Miller", securityGroups: ["Japan BU", "OBU"], role: "APPROVER" },
]

export const mockAssessments: Assessment[] = [
  {
    id: "1",
    name: "Phase III Crohn's Disease Trial - Belgium",
    studyTrackingNumber: "ST-2026-00123",
    businessUnit: "OBU",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
    status: "IN_REVIEW",
    proposalCount: 45,
    flaggedCount: 8,
    assignedTo: "Sarah Johnson",
    auditEvents: [
      { id: "ae-1-1", userName: "Sarah Johnson", action: "Assessment created", timestamp: "2024-01-15T10:00:00Z" },
      { id: "ae-1-2", userName: "Sarah Johnson", action: "Changed Status to In Review", timestamp: "2024-01-16T09:30:00Z" },
      { id: "ae-1-3", userName: "Mike Chen", action: "Changed Data Source to IQVIA GrantPlan", timestamp: "2024-01-17T14:15:00Z" },
      { id: "ae-1-4", userName: "Sarah Johnson", action: "Line item 'Principal Investigator' decision changed to Accepted", timestamp: "2024-01-20T14:30:00Z" },
    ],
  },
  {
    id: "2",
    name: "Phase II Breast Cancer Study - USA",
    studyTrackingNumber: "ST-2026-00456",
    businessUnit: "USBU",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-18T16:45:00Z",
    status: "IN_REVIEW",
    proposalCount: 5,
    flaggedCount: 1,
    assignedTo: "Mike Chen",
    auditEvents: [
      { id: "ae-2-1", userName: "Mike Chen", action: "Assessment created", timestamp: "2024-01-10T08:00:00Z" },
      { id: "ae-2-2", userName: "Mike Chen", action: "Changed Status to In Review", timestamp: "2024-01-12T11:00:00Z" },
    ],
  },
  {
    id: "3",
    name: "Phase I Alzheimer's Trial - Germany",
    studyTrackingNumber: "ST-2025-00789",
    businessUnit: "GME",
    dataSource: "IQVIA GPI",
    createdAt: "2024-01-05T09:15:00Z",
    updatedAt: "2024-01-22T11:20:00Z",
    status: "APPROVED",
    proposalCount: 4,
    flaggedCount: 1,
    assignedTo: "Emily Martinez",
    auditEvents: [
      { id: "ae-3-1", userName: "Emily Martinez", action: "Assessment created", timestamp: "2024-01-05T09:15:00Z" },
      { id: "ae-3-2", userName: "Emily Martinez", action: "Changed Data Source to IQVIA GPI", timestamp: "2024-01-10T13:45:00Z" },
      { id: "ae-3-3", userName: "Emily Martinez", action: "Changed Status to Approved", timestamp: "2024-01-22T11:20:00Z" },
    ],
  },
  {
    id: "4",
    name: "Phase III Heart Failure Study - Japan",
    studyTrackingNumber: "ST-2025-01042",
    businessUnit: "Japan BU",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2023-12-20T13:30:00Z",
    updatedAt: "2024-01-12T10:15:00Z",
    status: "IN_REVIEW",
    proposalCount: 5,
    flaggedCount: 0,
    assignedTo: "David Kim",
    auditEvents: [
      { id: "ae-4-1", userName: "David Kim", action: "Assessment created", timestamp: "2023-12-20T13:30:00Z" },
      { id: "ae-4-2", userName: "David Kim", action: "Export Report clicked", timestamp: "2024-01-05T09:00:00Z" },
    ],
  },
  {
    id: "5",
    name: "Phase II Rheumatoid Arthritis Trial - UK",
    studyTrackingNumber: "ST-2026-00587",
    businessUnit: "VBU",
    dataSource: "IQVIA GPI",
    createdAt: "2024-01-18T11:00:00Z",
    updatedAt: "2024-01-19T15:30:00Z",
    status: "MANUAL_ASSESSMENT",
    proposalCount: 4,
    flaggedCount: 1,
    assignedTo: "Lisa Wong",
    auditEvents: [
      { id: "ae-5-1", userName: "Lisa Wong", action: "Assessment created", timestamp: "2024-01-18T11:00:00Z" },
      { id: "ae-5-2", userName: "Lisa Wong", action: "Changed Status to Manual Assessment", timestamp: "2024-01-19T15:30:00Z" },
    ],
  },
  {
    id: "6",
    name: "Phase IV Type 2 Diabetes Study - France",
    studyTrackingNumber: "ST-2026-00215",
    businessUnit: "PDT",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-01-08T09:00:00Z",
    updatedAt: "2024-01-21T10:30:00Z",
    status: "APPROVED",
    proposalCount: 5,
    flaggedCount: 0,
    assignedTo: "James Miller",
    auditEvents: [
      { id: "ae-6-1", userName: "James Miller", action: "Assessment created", timestamp: "2024-01-08T09:00:00Z" },
      { id: "ae-6-2", userName: "James Miller", action: "Changed Status to Approved", timestamp: "2024-01-21T10:30:00Z" },
      { id: "ae-6-3", userName: "James Miller", action: "Download PDF clicked", timestamp: "2024-01-21T11:00:00Z" },
    ],
  },
  // --- Additional assessments: 2 more per BU to reach 3 each ---
  // USBU #2
  {
    id: "7",
    name: "Phase I Lung Cancer Screening - USA",
    studyTrackingNumber: "ST-2026-00701",
    businessUnit: "USBU",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-02-01T09:00:00Z",
    updatedAt: "2024-02-05T11:30:00Z",
    status: "APPROVED",
    proposalCount: 8,
    flaggedCount: 0,
    assignedTo: "Sarah Johnson",
    auditEvents: [
      { id: "ae-7-1", userName: "Sarah Johnson", action: "Assessment created", timestamp: "2024-02-01T09:00:00Z" },
      { id: "ae-7-2", userName: "Sarah Johnson", action: "Changed Status to Approved", timestamp: "2024-02-05T11:30:00Z" },
    ],
  },
  // USBU #3
  {
    id: "8",
    name: "Phase II Prostate Cancer Trial - USA",
    studyTrackingNumber: "ST-2026-00802",
    businessUnit: "USBU",
    dataSource: "IQVIA GPI",
    createdAt: "2024-02-10T08:00:00Z",
    updatedAt: "2024-02-15T14:00:00Z",
    status: "MANUAL_ASSESSMENT",
    proposalCount: 12,
    flaggedCount: 4,
    assignedTo: "Mike Chen",
    auditEvents: [
      { id: "ae-8-1", userName: "Mike Chen", action: "Assessment created", timestamp: "2024-02-10T08:00:00Z" },
    ],
  },
  // OBU #2
  {
    id: "9",
    name: "Phase II Ulcerative Colitis Study - Spain",
    studyTrackingNumber: "ST-2026-00903",
    businessUnit: "OBU",
    dataSource: "IQVIA GPI",
    createdAt: "2024-01-25T10:00:00Z",
    updatedAt: "2024-02-02T09:00:00Z",
    status: "APPROVED",
    proposalCount: 6,
    flaggedCount: 0,
    assignedTo: "Emily Martinez",
    auditEvents: [
      { id: "ae-9-1", userName: "Emily Martinez", action: "Assessment created", timestamp: "2024-01-25T10:00:00Z" },
      { id: "ae-9-2", userName: "Emily Martinez", action: "Changed Status to Approved", timestamp: "2024-02-02T09:00:00Z" },
    ],
  },
  // OBU #3
  {
    id: "10",
    name: "Phase III Celiac Disease Trial - Italy",
    studyTrackingNumber: "ST-2026-01004",
    businessUnit: "OBU",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-02-08T12:00:00Z",
    updatedAt: "2024-02-12T16:00:00Z",
    status: "IN_REVIEW",
    proposalCount: 10,
    flaggedCount: 3,
    assignedTo: "David Kim",
    auditEvents: [
      { id: "ae-10-1", userName: "David Kim", action: "Assessment created", timestamp: "2024-02-08T12:00:00Z" },
    ],
  },
  // GMA #2
  {
    id: "11",
    name: "Phase II Parkinson's Disease Study - Canada",
    studyTrackingNumber: "ST-2026-01105",
    businessUnit: "GME",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-01-20T09:30:00Z",
    updatedAt: "2024-01-28T15:00:00Z",
    status: "IN_REVIEW",
    proposalCount: 7,
    flaggedCount: 2,
    assignedTo: "Lisa Wong",
    auditEvents: [
      { id: "ae-11-1", userName: "Lisa Wong", action: "Assessment created", timestamp: "2024-01-20T09:30:00Z" },
    ],
  },
  // GMA #3
  {
    id: "12",
    name: "Phase IV Epilepsy Registry - Australia",
    studyTrackingNumber: "ST-2025-01206",
    businessUnit: "GME",
    dataSource: "IQVIA GPI",
    createdAt: "2023-12-15T08:00:00Z",
    updatedAt: "2024-01-10T10:00:00Z",
    status: "APPROVED",
    proposalCount: 3,
    flaggedCount: 0,
    assignedTo: "James Miller",
    auditEvents: [
      { id: "ae-12-1", userName: "James Miller", action: "Assessment created", timestamp: "2023-12-15T08:00:00Z" },
      { id: "ae-12-2", userName: "James Miller", action: "Changed Status to Approved", timestamp: "2024-01-10T10:00:00Z" },
    ],
  },
  // PDT #2
  {
    id: "13",
    name: "Phase III Hemophilia A Study - Switzerland",
    studyTrackingNumber: "ST-2026-01307",
    businessUnit: "PDT",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-01-12T14:00:00Z",
    updatedAt: "2024-01-22T09:00:00Z",
    status: "IN_REVIEW",
    proposalCount: 9,
    flaggedCount: 2,
    assignedTo: "Sarah Johnson",
    auditEvents: [
      { id: "ae-13-1", userName: "Sarah Johnson", action: "Assessment created", timestamp: "2024-01-12T14:00:00Z" },
    ],
  },
  // PDT #3
  {
    id: "14",
    name: "Phase I Immunoglobulin Therapy Trial - USA",
    studyTrackingNumber: "ST-2025-01408",
    businessUnit: "PDT",
    dataSource: "IQVIA GPI",
    createdAt: "2023-11-20T10:00:00Z",
    updatedAt: "2024-01-05T12:30:00Z",
    status: "APPROVED",
    proposalCount: 4,
    flaggedCount: 0,
    assignedTo: "Mike Chen",
    auditEvents: [
      { id: "ae-14-1", userName: "Mike Chen", action: "Assessment created", timestamp: "2023-11-20T10:00:00Z" },
      { id: "ae-14-2", userName: "Mike Chen", action: "Changed Status to Approved", timestamp: "2024-01-05T12:30:00Z" },
    ],
  },
  // VBU #2
  {
    id: "15",
    name: "Phase III Dengue Vaccine Study - Brazil",
    studyTrackingNumber: "ST-2026-01509",
    businessUnit: "VBU",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-01-30T09:00:00Z",
    updatedAt: "2024-02-08T11:00:00Z",
    status: "IN_REVIEW",
    proposalCount: 15,
    flaggedCount: 5,
    assignedTo: "Emily Martinez",
    auditEvents: [
      { id: "ae-15-1", userName: "Emily Martinez", action: "Assessment created", timestamp: "2024-01-30T09:00:00Z" },
    ],
  },
  // VBU #3
  {
    id: "16",
    name: "Phase II COVID Booster Trial - South Korea",
    studyTrackingNumber: "ST-2026-01610",
    businessUnit: "VBU",
    dataSource: "IQVIA GPI",
    createdAt: "2024-02-05T13:00:00Z",
    updatedAt: "2024-02-10T17:00:00Z",
    status: "APPROVED",
    proposalCount: 6,
    flaggedCount: 0,
    assignedTo: "David Kim",
    auditEvents: [
      { id: "ae-16-1", userName: "David Kim", action: "Assessment created", timestamp: "2024-02-05T13:00:00Z" },
      { id: "ae-16-2", userName: "David Kim", action: "Changed Status to Approved", timestamp: "2024-02-10T17:00:00Z" },
    ],
  },
  // JPBU #2
  {
    id: "17",
    name: "Phase II Gastric Cancer Study - Japan",
    studyTrackingNumber: "ST-2026-01711",
    businessUnit: "Japan BU",
    dataSource: "IQVIA GPI",
    createdAt: "2024-01-22T11:00:00Z",
    updatedAt: "2024-02-01T08:30:00Z",
    status: "APPROVED",
    proposalCount: 7,
    flaggedCount: 0,
    assignedTo: "James Miller",
    auditEvents: [
      { id: "ae-17-1", userName: "James Miller", action: "Assessment created", timestamp: "2024-01-22T11:00:00Z" },
      { id: "ae-17-2", userName: "James Miller", action: "Changed Status to Approved", timestamp: "2024-02-01T08:30:00Z" },
    ],
  },
  // JPBU #3
  {
    id: "18",
    name: "Phase I Atopic Dermatitis Trial - Japan",
    studyTrackingNumber: "ST-2026-01812",
    businessUnit: "Japan BU",
    dataSource: "IQVIA GrantPlan",
    createdAt: "2024-02-12T10:00:00Z",
    updatedAt: "2024-02-14T16:00:00Z",
    status: "MANUAL_ASSESSMENT",
    proposalCount: 5,
    flaggedCount: 2,
    assignedTo: "Lisa Wong",
    auditEvents: [
      { id: "ae-18-1", userName: "Lisa Wong", action: "Assessment created", timestamp: "2024-02-12T10:00:00Z" },
      { id: "ae-18-2", userName: "Lisa Wong", action: "Changed Status to Manual Assessment", timestamp: "2024-02-14T16:00:00Z" },
    ],
  },
]

// Assessment line items based on the internal assessment CSV structure
export const mockAssessmentLineItems: AssessmentLineItem[] = [
  {
    id: "li1",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Personnel",
    description: "Principal Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 10,
    unitPrice: 395,
    totalCost: 3950,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 395,
    acceptedTotalCost: 3950,
    decision: "Accepted",
    industryStandard: { low: 210, med: 320, high: 421, p90: 498, p100: 575 },
    source: "GP NP080",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li2",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Personnel",
    description: "Sub-Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 20,
    unitPrice: 263,
    totalCost: 5260,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 263,
    acceptedTotalCost: 5260,
    decision: "Accepted",
    industryStandard: { low: 135, med: 200, high: 263, p90: 339, p100: 410 },
    source: "GP SC003",
    noteLogic: "Accepted - at benchmark high",
  },
  {
    id: "li3",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Personnel",
    description: "Study Coordinator",
    unitType: "Hourly rate",
    numberOfUnits: 50,
    unitPrice: 86,
    totalCost: 4300,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 86,
    acceptedTotalCost: 4300,
    decision: "Accepted",
    industryStandard: { low: 48, med: 70, high: 91, p90: 105, p100: 128 },
    source: "GP SC003",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li4",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Personnel",
    description: "Research Nurse",
    unitType: "Hourly rate",
    numberOfUnits: 30,
    unitPrice: 79,
    totalCost: 2370,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 79,
    acceptedTotalCost: 2370,
    decision: "Accepted",
    industryStandard: { low: 42, med: 62, high: 80, p90: 97, p100: 118 },
    source: "GP NP020",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li5",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Personnel",
    description: "Lab Technician",
    unitType: "Hourly rate",
    numberOfUnits: 15,
    unitPrice: 121,
    totalCost: 1815,
    currency: "USD",
    costType: "Direct cost",
    decision: "Pending",
    industryStandard: { low: 55, med: 82, high: 105, p90: 118, p100: 145 },
    source: "GP LT001",
    noteLogic: "Above FMV - requires justification",
    questionComment: "Rate exceeds 90th percentile benchmark. Please provide justification for the higher rate.",
  },
  {
    id: "li6",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Material/supplies",
    description: "EDTA Tubes (pack of 100)",
    unitType: "Unit cost",
    numberOfUnits: 5,
    unitPrice: 45,
    totalCost: 225,
    currency: "USD",
    costType: "Direct invoiceable",
    decision: "Manual assessment",
    noteLogic: "No benchmark mapping available for this supply item",
    questionComment: "Benchmark data unavailable - requires manual FMV review.",
  },
  {
    id: "li7",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Material/supplies",
    description: "Specimen Collection Kits",
    unitType: "Unit cost",
    numberOfUnits: 50,
    unitPrice: 12,
    totalCost: 600,
    currency: "USD",
    costType: "Direct invoiceable",
    acceptedUnitPrice: 12,
    acceptedTotalCost: 600,
    decision: "Accepted",
    noteLogic: "Accepted - standard market rate",
  },
  {
    id: "li8",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Software",
    description: "EDC System Access License",
    unitType: "Fee",
    numberOfUnits: 1,
    unitPrice: 2500,
    totalCost: 2500,
    currency: "USD",
    costType: "Other cost-no overhead",
    acceptedUnitPrice: 2500,
    acceptedTotalCost: 2500,
    decision: "Accepted",
    noteLogic: "Accepted - standard licensing fee",
  },
  {
    id: "li9",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Software",
    description: "Data Analytics Platform License",
    unitType: "Fee",
    numberOfUnits: 1,
    unitPrice: 1800,
    totalCost: 1800,
    currency: "USD",
    costType: "Other cost-no overhead",
    decision: "Manual assessment",
    noteLogic: "Unsupported cost type - no benchmark available for software licenses",
    questionComment: "Software licensing fees require manual FMV assessment.",
  },
  {
    id: "li10",
    assessmentId: "1",
    site: "PI US",
    costCategory: "Fees",
    description: "IRB/Ethics Committee Fee",
    unitType: "Fee",
    numberOfUnits: 1,
    unitPrice: 3500,
    totalCost: 3500,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 3200,
    acceptedTotalCost: 3200,
    decision: "Not amended",
    industryStandard: { low: 1800, med: 2500, high: 3200, p90: 3800, p100: 4500 },
    source: "GP IRB01",
    noteLogic: "Proposed at high benchmark - accepted at standard rate",
  },
  {
    id: "li11",
    assessmentId: "1",
    site: "Brazil",
    costCategory: "Personnel",
    description: "Principal Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 8,
    unitPrice: 850,
    totalCost: 6800,
    currency: "BRL",
    costType: "Direct cost",
    acceptedUnitPrice: 850,
    acceptedTotalCost: 6800,
    decision: "Accepted",
    industryStandard: { low: 480, med: 700, high: 920, p90: 1050, p100: 1220 },
    source: "GP NP080",
    noteLogic: "Accepted - within FMV range for Brazil",
  },
  {
    id: "li12",
    assessmentId: "1",
    site: "Brazil",
    costCategory: "Personnel",
    description: "Study Coordinator",
    unitType: "Hourly rate",
    numberOfUnits: 40,
    unitPrice: 185,
    totalCost: 7400,
    currency: "BRL",
    costType: "Direct cost",
    acceptedUnitPrice: 185,
    acceptedTotalCost: 7400,
    decision: "Accepted",
    industryStandard: { low: 100, med: 150, high: 195, p90: 220, p100: 265 },
    source: "GP SC003",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li13",
    assessmentId: "1",
    site: "Brazil",
    costCategory: "Fees",
    description: "Local Ethics Committee Fee",
    unitType: "Fee",
    numberOfUnits: 1,
    unitPrice: 4500,
    totalCost: 4500,
    currency: "BRL",
    costType: "Direct cost",
    decision: "Not accepted",
    industryStandard: { low: 1500, med: 2300, high: 3000, p90: 3500, p100: 4200 },
    source: "GP IRB01",
    noteLogic: "Significantly above benchmark - not accepted",
    questionComment: "Fee exceeds benchmark by 50%. Please revise or provide documentation for the higher rate.",
  },
  {
    id: "li14",
    assessmentId: "1",
    site: "Brazil",
    costCategory: "Material/supplies",
    description: "Laboratory Consumables",
    unitType: "Unit cost",
    numberOfUnits: 100,
    unitPrice: 25,
    totalCost: 2500,
    currency: "BRL",
    costType: "Direct invoiceable",
    acceptedUnitPrice: 25,
    acceptedTotalCost: 2500,
    decision: "Accepted",
    noteLogic: "Accepted - standard market rate",
  },

  // Assessment 2 - Phase II Breast Cancer Study - USA
  {
    id: "li15",
    assessmentId: "2",
    site: "Site US-01",
    costCategory: "Personnel",
    description: "Principal Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 12,
    unitPrice: 450,
    totalCost: 5400,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 420,
    acceptedTotalCost: 5040,
    decision: "Not amended",
    industryStandard: { low: 220, med: 330, high: 430, p90: 510, p100: 590 },
    source: "GP NP080",
    noteLogic: "Proposed above 90th percentile - accepted at adjusted rate",
  },
  {
    id: "li16",
    assessmentId: "2",
    site: "Site US-01",
    costCategory: "Personnel",
    description: "Oncology Nurse",
    unitType: "Hourly rate",
    numberOfUnits: 40,
    unitPrice: 95,
    totalCost: 3800,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 95,
    acceptedTotalCost: 3800,
    decision: "Accepted",
    industryStandard: { low: 45, med: 68, high: 88, p90: 102, p100: 125 },
    source: "GP NP020",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li17",
    assessmentId: "2",
    site: "Site US-01",
    costCategory: "Personnel",
    description: "Data Manager",
    unitType: "Hourly rate",
    numberOfUnits: 25,
    unitPrice: 78,
    totalCost: 1950,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 78,
    acceptedTotalCost: 1950,
    decision: "Accepted",
    industryStandard: { low: 38, med: 55, high: 72, p90: 85, p100: 105 },
    source: "GP SC003",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li18",
    assessmentId: "2",
    site: "Site US-01",
    costCategory: "Fees",
    description: "Institutional Overhead",
    unitType: "Fee",
    numberOfUnits: 1,
    unitPrice: 5200,
    totalCost: 5200,
    currency: "USD",
    costType: "Other cost-no overhead",
    decision: "Pending",
    industryStandard: { low: 2500, med: 3500, high: 4500, p90: 5000, p100: 5800 },
    source: "GP IRB01",
    noteLogic: "Above high benchmark - pending review",
    questionComment: "Overhead fee exceeds benchmark high. Awaiting institutional justification.",
  },
  {
    id: "li19",
    assessmentId: "2",
    site: "Site US-02",
    costCategory: "Personnel",
    description: "Sub-Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 18,
    unitPrice: 310,
    totalCost: 5580,
    currency: "USD",
    costType: "Direct cost",
    acceptedUnitPrice: 310,
    acceptedTotalCost: 5580,
    decision: "Accepted",
    industryStandard: { low: 150, med: 220, high: 290, p90: 360, p100: 430 },
    source: "GP SC003",
    noteLogic: "Accepted - within FMV range",
  },

  // Assessment 3 - Phase I Alzheimer's Trial - Germany
  {
    id: "li20",
    assessmentId: "3",
    site: "Site DE-01",
    costCategory: "Personnel",
    description: "Principal Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 10,
    unitPrice: 320,
    totalCost: 3200,
    currency: "EUR",
    costType: "Direct cost",
    acceptedUnitPrice: 320,
    acceptedTotalCost: 3200,
    decision: "Accepted",
    industryStandard: { low: 180, med: 270, high: 350, p90: 410, p100: 480 },
    source: "GM NE050",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li21",
    assessmentId: "3",
    site: "Site DE-01",
    costCategory: "Personnel",
    description: "Neuropsychologist",
    unitType: "Hourly rate",
    numberOfUnits: 20,
    unitPrice: 195,
    totalCost: 3900,
    currency: "EUR",
    costType: "Direct cost",
    acceptedUnitPrice: 195,
    acceptedTotalCost: 3900,
    decision: "Accepted",
    industryStandard: { low: 95, med: 140, high: 180, p90: 215, p100: 260 },
    source: "GM NE051",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li22",
    assessmentId: "3",
    site: "Site DE-01",
    costCategory: "Personnel",
    description: "Study Coordinator",
    unitType: "Hourly rate",
    numberOfUnits: 35,
    unitPrice: 72,
    totalCost: 2520,
    currency: "EUR",
    costType: "Direct cost",
    acceptedUnitPrice: 72,
    acceptedTotalCost: 2520,
    decision: "Accepted",
    industryStandard: { low: 38, med: 58, high: 75, p90: 88, p100: 108 },
    source: "GM SC010",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li23",
    assessmentId: "3",
    site: "Site DE-01",
    costCategory: "Fees",
    description: "MRI Brain Scan",
    unitType: "Fee",
    numberOfUnits: 6,
    unitPrice: 680,
    totalCost: 4080,
    currency: "EUR",
    costType: "Direct cost",
    decision: "Not accepted",
    industryStandard: { low: 280, med: 400, high: 520, p90: 610, p100: 740 },
    source: "GM IM020",
    noteLogic: "Significantly above 90th percentile - not accepted",
    questionComment: "MRI costs exceed benchmark. Requesting breakdown of imaging charges.",
  },

  // Assessment 4 - Phase III Heart Failure Study - Japan
  {
    id: "li24",
    assessmentId: "4",
    site: "Site JP-01",
    costCategory: "Personnel",
    description: "Principal Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 15,
    unitPrice: 42000,
    totalCost: 630000,
    currency: "JPY",
    costType: "Direct cost",
    acceptedUnitPrice: 42000,
    acceptedTotalCost: 630000,
    decision: "Accepted",
    industryStandard: { low: 25000, med: 35000, high: 45000, p90: 52000, p100: 62000 },
    source: "GP CV010",
    noteLogic: "Accepted - within FMV range for Japan",
  },
  {
    id: "li25",
    assessmentId: "4",
    site: "Site JP-01",
    costCategory: "Personnel",
    description: "Cardiologist",
    unitType: "Hourly rate",
    numberOfUnits: 20,
    unitPrice: 38000,
    totalCost: 760000,
    currency: "JPY",
    costType: "Direct cost",
    acceptedUnitPrice: 38000,
    acceptedTotalCost: 760000,
    decision: "Accepted",
    industryStandard: { low: 22000, med: 32000, high: 40000, p90: 46000, p100: 55000 },
    source: "GP CV011",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li26",
    assessmentId: "4",
    site: "Site JP-01",
    costCategory: "Personnel",
    description: "Study Coordinator",
    unitType: "Hourly rate",
    numberOfUnits: 50,
    unitPrice: 8500,
    totalCost: 425000,
    currency: "JPY",
    costType: "Direct cost",
    acceptedUnitPrice: 8500,
    acceptedTotalCost: 425000,
    decision: "Accepted",
    industryStandard: { low: 5000, med: 7000, high: 9000, p90: 10500, p100: 12800 },
    source: "GP SC003",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li27",
    assessmentId: "4",
    site: "Site JP-02",
    costCategory: "Personnel",
    description: "Research Nurse",
    unitType: "Hourly rate",
    numberOfUnits: 30,
    unitPrice: 7200,
    totalCost: 216000,
    currency: "JPY",
    costType: "Direct cost",
    acceptedUnitPrice: 7200,
    acceptedTotalCost: 216000,
    decision: "Accepted",
    industryStandard: { low: 4000, med: 5800, high: 7500, p90: 8800, p100: 10500 },
    source: "GP NP020",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li28",
    assessmentId: "4",
    site: "Site JP-02",
    costCategory: "Fees",
    description: "Echocardiogram",
    unitType: "Fee",
    numberOfUnits: 8,
    unitPrice: 18000,
    totalCost: 144000,
    currency: "JPY",
    costType: "Direct cost",
    acceptedUnitPrice: 18000,
    acceptedTotalCost: 144000,
    decision: "Accepted",
    industryStandard: { low: 9000, med: 13000, high: 16500, p90: 19500, p100: 23000 },
    source: "GP CV020",
    noteLogic: "Accepted - within FMV range",
  },

  // Assessment 5 - Phase II Rheumatoid Arthritis Trial - UK
  {
    id: "li29",
    assessmentId: "5",
    site: "Site UK-01",
    costCategory: "Personnel",
    description: "Principal Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 10,
    unitPrice: 310,
    totalCost: 3100,
    currency: "GBP",
    costType: "Direct cost",
    decision: "Pending",
    industryStandard: { low: 145, med: 215, high: 280, p90: 330, p100: 395 },
    source: "GM IM040",
    noteLogic: "Within FMV range - pending final review",
  },
  {
    id: "li30",
    assessmentId: "5",
    site: "Site UK-01",
    costCategory: "Personnel",
    description: "Rheumatology Nurse",
    unitType: "Hourly rate",
    numberOfUnits: 35,
    unitPrice: 62,
    totalCost: 2170,
    currency: "GBP",
    costType: "Direct cost",
    decision: "Pending",
    industryStandard: { low: 30, med: 45, high: 58, p90: 68, p100: 82 },
    source: "GM NP030",
    noteLogic: "Within FMV range - pending final review",
  },
  {
    id: "li31",
    assessmentId: "5",
    site: "Site UK-01",
    costCategory: "Personnel",
    description: "Pharmacist",
    unitType: "Hourly rate",
    numberOfUnits: 12,
    unitPrice: 85,
    totalCost: 1020,
    currency: "GBP",
    costType: "Direct cost",
    decision: "Manual assessment",
    industryStandard: { low: 36, med: 54, high: 70, p90: 82, p100: 100 },
    source: "GM PH010",
    noteLogic: "Above 90th percentile - manual assessment required",
    questionComment: "Pharmacist rate exceeds benchmark. Need justification for specialist rate.",
  },
  {
    id: "li32",
    assessmentId: "5",
    site: "Site UK-01",
    costCategory: "Fees",
    description: "X-Ray Hands/Wrists",
    unitType: "Fee",
    numberOfUnits: 4,
    unitPrice: 125,
    totalCost: 500,
    currency: "GBP",
    costType: "Direct cost",
    decision: "Pending",
    industryStandard: { low: 60, med: 85, high: 110, p90: 130, p100: 155 },
    source: "GM IM045",
    noteLogic: "Within FMV range - pending review",
  },

  // Assessment 6 - Phase IV Type 2 Diabetes Study - France
  {
    id: "li33",
    assessmentId: "6",
    site: "Site FR-01",
    costCategory: "Personnel",
    description: "Principal Investigator",
    unitType: "Hourly rate",
    numberOfUnits: 8,
    unitPrice: 290,
    totalCost: 2320,
    currency: "EUR",
    costType: "Direct cost",
    acceptedUnitPrice: 290,
    acceptedTotalCost: 2320,
    decision: "Accepted",
    industryStandard: { low: 160, med: 240, high: 310, p90: 365, p100: 430 },
    source: "GP DM020",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li34",
    assessmentId: "6",
    site: "Site FR-01",
    costCategory: "Personnel",
    description: "Endocrinologist",
    unitType: "Hourly rate",
    numberOfUnits: 15,
    unitPrice: 260,
    totalCost: 3900,
    currency: "EUR",
    costType: "Direct cost",
    acceptedUnitPrice: 260,
    acceptedTotalCost: 3900,
    decision: "Accepted",
    industryStandard: { low: 140, med: 210, high: 275, p90: 320, p100: 385 },
    source: "GP DM021",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li35",
    assessmentId: "6",
    site: "Site FR-01",
    costCategory: "Personnel",
    description: "Study Coordinator",
    unitType: "Hourly rate",
    numberOfUnits: 30,
    unitPrice: 68,
    totalCost: 2040,
    currency: "EUR",
    costType: "Direct cost",
    acceptedUnitPrice: 68,
    acceptedTotalCost: 2040,
    decision: "Accepted",
    industryStandard: { low: 35, med: 52, high: 70, p90: 82, p100: 100 },
    source: "GP SC003",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li36",
    assessmentId: "6",
    site: "Site FR-01",
    costCategory: "Fees",
    description: "HbA1c Lab Test",
    unitType: "Fee",
    numberOfUnits: 12,
    unitPrice: 42,
    totalCost: 504,
    currency: "EUR",
    costType: "Direct cost",
    acceptedUnitPrice: 42,
    acceptedTotalCost: 504,
    decision: "Accepted",
    industryStandard: { low: 20, med: 30, high: 38, p90: 45, p100: 55 },
    source: "GP LB010",
    noteLogic: "Accepted - within FMV range",
  },
  {
    id: "li37",
    assessmentId: "6",
    site: "Site FR-02",
    costCategory: "Personnel",
    description: "Research Nurse",
    unitType: "Hourly rate",
    numberOfUnits: 25,
    unitPrice: 58,
    totalCost: 1450,
    currency: "EUR",
    costType: "Direct cost",
    acceptedUnitPrice: 58,
    acceptedTotalCost: 1450,
    decision: "Accepted",
    industryStandard: { low: 28, med: 42, high: 55, p90: 65, p100: 78 },
    source: "GP NP020",
    noteLogic: "Accepted - within FMV range",
  },
]

// Generate comparisons from line items
export const mockAssessmentComparisons: AssessmentComparison[] = mockAssessmentLineItems
  .filter((item) => item.industryStandard)
  .map((item) => {
    const benchmark90th = item.industryStandard?.p90 || item.industryStandard?.high || 0
    const variance = item.unitPrice - benchmark90th
    const variancePercent = benchmark90th > 0 ? (variance / benchmark90th) * 100 : 0
    
    let flag: "GREEN" | "YELLOW" | "RED" = "GREEN"
    if (variancePercent > 15) flag = "RED"
    else if (variancePercent > 5) flag = "YELLOW"
    
    return {
      id: `c-${item.id}`,
      lineItem: item,
      benchmarkLow: item.industryStandard?.low,
      benchmarkMed: item.industryStandard?.med,
      benchmarkHigh: item.industryStandard?.high,
      benchmark90th: item.industryStandard?.p90,
      benchmarkHighPercentile: item.industryStandard?.p100,
      selectedBenchmarkType: "p90" as const,
      variance,
      variancePercent,
      flag,
      aiSuggestion: flag === "RED" 
        ? `Unit price of ${item.unitPrice} ${item.currency} exceeds the 90th percentile benchmark of ${benchmark90th}. Consider negotiating or requesting justification.`
        : flag === "YELLOW"
        ? `Unit price is slightly above benchmark. Current pricing is within acceptable range but negotiation may yield savings.`
        : undefined,
      benchmarkDescription: item.source
        ? `${item.source.startsWith("GP") ? "IQVIA GrantPlan" : "IQVIA GPI GrantsManager"} — ${item.source} | ${item.costCategory}, ${item.unitType}`
        : undefined,
      comment: flag === "RED"
        ? "Exceeds benchmark - escalated for review"
        : flag === "YELLOW"
        ? "Slightly above benchmark - monitor"
        : item.decision === "Not accepted"
        ? "Rejected - vendor notified for revision"
        : item.decision === "Manual assessment"
        ? "Requires manual FMV review"
        : "",
    }
  })

export const mockBenchmarkFiles: BenchmarkFile[] = [
  {
    id: "bf1",
    fileName: "GrantPlan_Belgium_IBD_PhaseIII_2024.csv",
    country: "Belgium",
    indication: "Inflammatory Bowel Disease (IBD)",
    indicationCode: "K50-K52",
    trialPhase: "Phase III",
    currency: "EUR",
    source: "IQVIA_GRANTPLAN",
    studyCode: "IBD-2024-BE",
    patientType: "Adult",
    budgetType: "Per Patient",
    overheadPercent: 25,
    procedureCount: 182,
    uploadedAt: "2024-01-15T10:30:00Z",
    uploadedBy: "Sarah Johnson",
  },
  {
    id: "bf2",
    fileName: "GrantPlan_USA_Oncology_PhaseII_2024.csv",
    country: "United States",
    indication: "Oncology - Breast Cancer",
    indicationCode: "C50",
    trialPhase: "Phase II",
    currency: "USD",
    source: "IQVIA_GRANTPLAN",
    studyCode: "ONC-BC-2024",
    patientType: "Adult",
    budgetType: "Per Patient",
    overheadPercent: 30,
    procedureCount: 156,
    uploadedAt: "2024-01-12T14:15:00Z",
    uploadedBy: "Mike Chen",
  },
  {
    id: "bf3",
    fileName: "GrantsManager_Germany_Neurology_PhaseI.csv",
    country: "Germany",
    indication: "Neurology - Alzheimer's Disease",
    indicationCode: "G30",
    trialPhase: "Phase I",
    currency: "EUR",
    source: "IQVIA_GPI_GRANTSMANAGER",
    studyCode: "NEURO-ALZ-01",
    patientType: "Elderly",
    budgetType: "Per Visit",
    overheadPercent: 20,
    procedureCount: 98,
    uploadedAt: "2024-01-10T09:00:00Z",
    uploadedBy: "Emily Martinez",
  },
  {
    id: "bf4",
    fileName: "GrantPlan_Japan_Cardiovascular_PhaseIII.csv",
    country: "Japan",
    indication: "Cardiovascular - Heart Failure",
    indicationCode: "I50",
    trialPhase: "Phase III",
    currency: "JPY",
    source: "IQVIA_GRANTPLAN",
    studyCode: "CV-HF-JP-03",
    patientType: "Adult",
    budgetType: "Per Patient",
    overheadPercent: 25,
    procedureCount: 143,
    uploadedAt: "2024-01-08T16:45:00Z",
    uploadedBy: "David Kim",
  },
  {
    id: "bf5",
    fileName: "GrantsManager_UK_Immunology_PhaseII.csv",
    country: "United Kingdom",
    indication: "Immunology - Rheumatoid Arthritis",
    indicationCode: "M05-M06",
    trialPhase: "Phase II",
    currency: "GBP",
    source: "IQVIA_GPI_GRANTSMANAGER",
    studyCode: "IMM-RA-UK-02",
    patientType: "Adult",
    budgetType: "Per Patient",
    overheadPercent: 22,
    procedureCount: 112,
    uploadedAt: "2024-01-05T11:30:00Z",
    uploadedBy: "Sarah Johnson",
  },
  {
    id: "bf6",
    fileName: "GrantPlan_France_Diabetes_PhaseIV.csv",
    country: "France",
    indication: "Diabetes - Type 2",
    indicationCode: "E11",
    trialPhase: "Phase IV",
    currency: "EUR",
    source: "IQVIA_GRANTPLAN",
    studyCode: "DM-T2-FR-04",
    patientType: "Adult",
    budgetType: "Per Visit",
    overheadPercent: 18,
    procedureCount: 87,
    uploadedAt: "2024-01-03T08:00:00Z",
    uploadedBy: "Mike Chen",
  },
]

// Sample procedures for the Belgium IBD benchmark (bf1)
export const mockBenchmarkProcedures: BenchmarkProcedure[] = [
  {
    id: "bp1",
    benchmarkFileId: "bf1",
    code: "99213",
    procedure: "Office Visit - Established Patient, Level 3",
    quantity: 8,
    overhead: 25,
    cost: 125,
    total: 1250,
    tkdaMed: 118,
    industryLow: 95,
    industryMed: 118,
    industryHigh: 142,
    industry90th: 156,
    industry100th: 185,
    sourceType: "A",
  },
  {
    id: "bp2",
    benchmarkFileId: "bf1",
    code: "99214",
    procedure: "Office Visit - Established Patient, Level 4",
    quantity: 4,
    overhead: 25,
    cost: 185,
    total: 925,
    tkdaMed: 175,
    industryLow: 145,
    industryMed: 175,
    industryHigh: 210,
    industry90th: 228,
    industry100th: 265,
    sourceType: "A",
  },
  {
    id: "bp3",
    benchmarkFileId: "bf1",
    code: "36415",
    procedure: "Routine Venipuncture",
    quantity: 12,
    overhead: 25,
    cost: 25,
    total: 375,
    tkdaMed: 22,
    industryLow: 15,
    industryMed: 22,
    industryHigh: 32,
    industry90th: 38,
    industry100th: 45,
    sourceType: "A",
  },
  {
    id: "bp4",
    benchmarkFileId: "bf1",
    code: "80053",
    procedure: "Comprehensive Metabolic Panel",
    quantity: 6,
    overhead: 25,
    cost: 45,
    total: 337.5,
    tkdaMed: 42,
    industryLow: 28,
    industryMed: 42,
    industryHigh: 58,
    industry90th: 68,
    industry100th: 85,
    sourceType: "A",
  },
  {
    id: "bp5",
    benchmarkFileId: "bf1",
    code: "82728",
    procedure: "Ferritin",
    quantity: 4,
    overhead: 25,
    cost: 38,
    total: 190,
    tkdaMed: 35,
    industryLow: 22,
    industryMed: 35,
    industryHigh: 48,
    industry90th: 55,
    industry100th: 72,
    sourceType: "A",
  },
  {
    id: "bp6",
    benchmarkFileId: "bf1",
    code: "83036",
    procedure: "Hemoglobin A1C",
    quantity: 4,
    overhead: 25,
    cost: 52,
    total: 260,
    tkdaMed: 48,
    industryLow: 32,
    industryMed: 48,
    industryHigh: 65,
    industry90th: 75,
    industry100th: 92,
    sourceType: "A",
  },
  {
    id: "bp7",
    benchmarkFileId: "bf1",
    code: "88305",
    procedure: "Surgical Pathology - Level IV",
    quantity: 2,
    overhead: 25,
    cost: 285,
    total: 712.5,
    tkdaMed: 265,
    industryLow: 185,
    industryMed: 265,
    industryHigh: 345,
    industry90th: 395,
    industry100th: 485,
    sourceType: "A",
  },
  {
    id: "bp8",
    benchmarkFileId: "bf1",
    code: "45378",
    procedure: "Colonoscopy - Diagnostic",
    quantity: 2,
    overhead: 25,
    cost: 850,
    total: 2125,
    tkdaMed: 795,
    industryLow: 625,
    industryMed: 795,
    industryHigh: 985,
    industry90th: 1125,
    industry100th: 1350,
    sourceType: "A",
  },
  {
    id: "bp9",
    benchmarkFileId: "bf1",
    code: "45380",
    procedure: "Colonoscopy with Biopsy",
    quantity: 1,
    overhead: 25,
    cost: 1150,
    total: 1437.5,
    tkdaMed: 1085,
    industryLow: 875,
    industryMed: 1085,
    industryHigh: 1325,
    industry90th: 1485,
    industry100th: 1750,
    sourceType: "A",
  },
  {
    id: "bp10",
    benchmarkFileId: "bf1",
    code: "74160",
    procedure: "CT Abdomen with Contrast",
    quantity: 1,
    overhead: 25,
    cost: 485,
    total: 606.25,
    tkdaMed: 455,
    industryLow: 325,
    industryMed: 455,
    industryHigh: 595,
    industry90th: 685,
    industry100th: 825,
    sourceType: "A",
  },
  {
    id: "bp11",
    benchmarkFileId: "bf1",
    code: "COORD-01",
    procedure: "Study Coordinator Time (per hour)",
    quantity: 15,
    overhead: 25,
    cost: 65,
    total: 1218.75,
    tkdaMed: 58,
    industryLow: 42,
    industryMed: 58,
    industryHigh: 78,
    industry90th: 92,
    industry100th: 115,
    sourceType: "PL",
  },
  {
    id: "bp12",
    benchmarkFileId: "bf1",
    code: "PI-01",
    procedure: "Principal Investigator Time (per hour)",
    quantity: 8,
    overhead: 25,
    cost: 225,
    total: 2250,
    tkdaMed: 210,
    industryLow: 165,
    industryMed: 210,
    industryHigh: 265,
    industry90th: 305,
    industry100th: 375,
    sourceType: "PL",
  },
  {
    id: "bp13",
    benchmarkFileId: "bf1",
    code: "PHARM-01",
    procedure: "Pharmacy Dispensing Fee",
    quantity: 12,
    overhead: 25,
    cost: 85,
    total: 1275,
    tkdaMed: 78,
    industryLow: 55,
    industryMed: 78,
    industryHigh: 105,
    industry90th: 125,
    industry100th: 155,
    sourceType: "A",
  },
  {
    id: "bp14",
    benchmarkFileId: "bf1",
    code: "ARCH-01",
    procedure: "Archiving Fee",
    quantity: 1,
    overhead: 25,
    cost: 350,
    total: 437.5,
    industryLow: 200,
    industryMed: 320,
    industryHigh: 450,
    industry90th: 525,
    industry100th: 650,
    sourceType: "E",
  },
]
