-- Country to Currency mapping table
CREATE TABLE IF NOT EXISTS country_currencies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country TEXT UNIQUE NOT NULL,
  currency_code TEXT NOT NULL,
  currency_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the country-currency mappings
INSERT INTO country_currencies (country, currency_code) VALUES
  ('Albania', 'ALL'),
  ('Argentina', 'USD'),
  ('Australia', 'AUD'),
  ('Austria', 'EUR'),
  ('Belgium', 'EUR'),
  ('Bosnia-Hercegovina', 'BAM'),
  ('Brazil', 'BRL'),
  ('Bulgaria', 'BGN'),
  ('Cambodia', 'KHR'),
  ('Canada', 'CAD'),
  ('Chile', 'CLP'),
  ('China', 'CNY'),
  ('Colombia', 'COP'),
  ('Croatia', 'EUR'),
  ('Cyprus', 'EUR'),
  ('Czech Republic', 'CZK'),
  ('Denmark', 'DKK'),
  ('Egypt', 'EGP'),
  ('Estonia', 'EUR'),
  ('Finland', 'EUR'),
  ('France', 'EUR'),
  ('Germany', 'EUR'),
  ('Greece', 'EUR'),
  ('Hong Kong', 'HKD'),
  ('Hungary', 'HUF'),
  ('Iceland', 'ISK'),
  ('India', 'INR'),
  ('Ireland', 'EUR'),
  ('Israel', 'NIS'),
  ('Italy', 'EUR'),
  ('Japan', 'JPY'),
  ('Kazakhstan', 'KZT'),
  ('Kuwait', 'KWD'),
  ('Latvia', 'EUR'),
  ('Lebanon', 'LBP'),
  ('Lithuania', 'EUR'),
  ('Macedonia', 'MKD'),
  ('Malta', 'EUR'),
  ('Mexico', 'MXN'),
  ('Morocco', 'MAD'),
  ('Netherlands', 'EUR'),
  ('Norway', 'NOK'),
  ('Oman', 'OMR'),
  ('Peru', 'PEN'),
  ('Poland', 'PLN'),
  ('Portugal', 'EUR'),
  ('Qatar', 'QAR'),
  ('Romania', 'RON'),
  ('Russia', 'RUB'),
  ('Saudi Arabia', 'SAR'),
  ('Serbia', 'RSD'),
  ('Singapore', 'SGD'),
  ('Slovak Republic', 'EUR'),
  ('Slovenia', 'EUR'),
  ('South Africa', 'ZAR'),
  ('South Korea', 'KRW'),
  ('Spain', 'EUR'),
  ('Sweden', 'SEK'),
  ('Switzerland', 'CHF'),
  ('Taiwan', 'TWD'),
  ('Tanzania', 'TZS'),
  ('Thailand', 'THB'),
  ('Tunisia', 'TND'),
  ('Turkey', 'USD'),
  ('United Arab Emirates', 'AED'),
  ('United Kingdom', 'GBP'),
  ('United States', 'USD'),
  ('Venezuela', 'USD'),
  ('Vietnam', 'VND')
ON CONFLICT (country) DO UPDATE SET 
  currency_code = EXCLUDED.currency_code,
  updated_at = NOW();

-- Disable RLS on this table (for now)
ALTER TABLE country_currencies DISABLE ROW LEVEL SECURITY;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_country_currencies_country ON country_currencies(country);
